---
- hosts: all
  gather_facts: no

  tasks:
  -  name: ZFSaware Root FS usage
     shell: zpool list rpool |grep -v ALLOC |awk '{print $3}'
     register: dfrootz
  -  name: nonzfs rootfs usage
     shell: df -h / |grep -v "Use" |awk '{print $5}'
     register: dfrootnz

  -  debug:
       msg: "System {{ inventory_hostname }}'s root FS utilization is {{ dfrootz.stdout }} {{ dfrootnz.stdout }}"
