---
- hosts: all
  gather_facts: no

  tasks:
  -  name: ZFSaware Root FS usage
     shell: [ $(df -hT / |grep -c zfs) -gt 0 ] && zpool list rpool |grep -v ALLOC |awk '{print $3}' || (df -h / |grep -v Use |awk '{print $5}')
     register: dfroot

  -  debug:
       msg: "System {{ inventory_hostname }}'s root FS utilization is {{ dfroot.stdout }}"
